# Generated by Django 5.1.7 on 2025-04-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="e@mail.com", max_length=254),
            preserve_default=False,
        ),
    ]
