# Generated by Django 5.1.7 on 2025-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tag_post_tags_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.CharField(max_length=100),
        ),
    ]
